package com.datayes.framework.orm.dao.model;

import java.util.Date;

public class NewsMetadata {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_detail_backup.news_id
     *
     * @mbggenerated Mon Dec 08 15:48:54 CST 2014
     */
    private Long newsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_detail_backup.insert_time
     *
     * @mbggenerated Mon Dec 08 15:48:54 CST 2014
     */
    private Date insertTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_detail_backup.update_time
     *
     * @mbggenerated Mon Dec 08 15:48:54 CST 2014
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_detail_backup.source_name
     *
     * @mbggenerated Mon Dec 08 15:48:54 CST 2014
     */
    private String sourceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_detail_backup.news_author
     *
     * @mbggenerated Mon Dec 08 15:48:54 CST 2014
     */
    private String newsAuthor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_detail_backup.news_url
     *
     * @mbggenerated Mon Dec 08 15:48:54 CST 2014
     */
    private String newsUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_detail_backup.news_title
     *
     * @mbggenerated Mon Dec 08 15:48:54 CST 2014
     */
    private String newsTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_detail_backup.news_fetch_time
     *
     * @mbggenerated Mon Dec 08 15:48:54 CST 2014
     */
    private Date newsFetchTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_detail_backup.news_site_name
     *
     * @mbggenerated Mon Dec 08 15:48:54 CST 2014
     */
    private String newsSiteName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_detail_backup.news_publish_time
     *
     * @mbggenerated Mon Dec 08 15:48:54 CST 2014
     */
    private Date newsPublishTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_detail_backup.news_comments_num
     *
     * @mbggenerated Mon Dec 08 15:48:54 CST 2014
     */
    private Integer newsCommentsNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_detail_backup.hashValue
     *
     * @mbggenerated Mon Dec 08 15:48:54 CST 2014
     */
    private String hashvalue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_detail_backup.has_summary
     *
     * @mbggenerated Mon Dec 08 15:48:54 CST 2014
     */
    private Byte hasSummary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_detail_backup.isActive
     *
     * @mbggenerated Mon Dec 08 15:48:54 CST 2014
     */
    private Byte isactive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_detail_backup.source_type
     *
     * @mbggenerated Mon Dec 08 15:48:54 CST 2014
     */
    private String sourceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_detail_backup.usefull
     *
     * @mbggenerated Mon Dec 08 15:48:54 CST 2014
     */
    private Byte usefull;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_detail_backup.group_id
     *
     * @mbggenerated Mon Dec 08 15:48:54 CST 2014
     */
    private Long groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_detail_backup.auto_update_time
     *
     * @mbggenerated Mon Dec 08 15:48:54 CST 2014
     */
    private Date autoUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_detail_backup.page_tag
     *
     * @mbggenerated Mon Dec 08 15:48:54 CST 2014
     */
    private String pageTag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_detail_backup.news_body
     *
     * @mbggenerated Mon Dec 08 15:48:54 CST 2014
     */

    private Integer infoType;

    private Byte publishStatus;

    private Integer isHeadline;

    private Integer isEdited;

    private String editor;
    
    private Date effectiveTime;


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_detail_backup.news_id
     *
     * @return the value of news_detail_backup.news_id
     * @mbggenerated Mon Dec 08 15:48:54 CST 2014
     */
    public Long getNewsId() {
        return newsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_detail_backup.news_id
     *
     * @param newsId the value for news_detail_backup.news_id
     * @mbggenerated Mon Dec 08 15:48:54 CST 2014
     */
    public void setNewsId(Long newsId) {
        this.newsId = newsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_detail_backup.insert_time
     *
     * @return the value of news_detail_backup.insert_time
     * @mbggenerated Mon Dec 08 15:48:54 CST 2014
     */
    public Date getInsertTime() {
        return insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_detail_backup.insert_time
     *
     * @param insertTime the value for news_detail_backup.insert_time
     * @mbggenerated Mon Dec 08 15:48:54 CST 2014
     */
    public void setInsertTime(Date insertTime) {
        this.insertTime = insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_detail_backup.update_time
     *
     * @return the value of news_detail_backup.update_time
     * @mbggenerated Mon Dec 08 15:48:54 CST 2014
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_detail_backup.update_time
     *
     * @param updateTime the value for news_detail_backup.update_time
     * @mbggenerated Mon Dec 08 15:48:54 CST 2014
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_detail_backup.source_name
     *
     * @return the value of news_detail_backup.source_name
     * @mbggenerated Mon Dec 08 15:48:54 CST 2014
     */
    public String getSourceName() {
        return sourceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_detail_backup.source_name
     *
     * @param sourceName the value for news_detail_backup.source_name
     * @mbggenerated Mon Dec 08 15:48:54 CST 2014
     */
    public void setSourceName(String sourceName) {
        this.sourceName = sourceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_detail_backup.news_author
     *
     * @return the value of news_detail_backup.news_author
     * @mbggenerated Mon Dec 08 15:48:54 CST 2014
     */
    public String getNewsAuthor() {
        return newsAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_detail_backup.news_author
     *
     * @param newsAuthor the value for news_detail_backup.news_author
     * @mbggenerated Mon Dec 08 15:48:54 CST 2014
     */
    public void setNewsAuthor(String newsAuthor) {
        this.newsAuthor = newsAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_detail_backup.news_url
     *
     * @return the value of news_detail_backup.news_url
     * @mbggenerated Mon Dec 08 15:48:54 CST 2014
     */
    public String getNewsUrl() {
        return newsUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_detail_backup.news_url
     *
     * @param newsUrl the value for news_detail_backup.news_url
     * @mbggenerated Mon Dec 08 15:48:54 CST 2014
     */
    public void setNewsUrl(String newsUrl) {
        this.newsUrl = newsUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_detail_backup.news_title
     *
     * @return the value of news_detail_backup.news_title
     * @mbggenerated Mon Dec 08 15:48:54 CST 2014
     */
    public String getNewsTitle() {
        return newsTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_detail_backup.news_title
     *
     * @param newsTitle the value for news_detail_backup.news_title
     * @mbggenerated Mon Dec 08 15:48:54 CST 2014
     */
    public void setNewsTitle(String newsTitle) {
        this.newsTitle = newsTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_detail_backup.news_fetch_time
     *
     * @return the value of news_detail_backup.news_fetch_time
     * @mbggenerated Mon Dec 08 15:48:54 CST 2014
     */
    public Date getNewsFetchTime() {
        return newsFetchTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_detail_backup.news_fetch_time
     *
     * @param newsFetchTime the value for news_detail_backup.news_fetch_time
     * @mbggenerated Mon Dec 08 15:48:54 CST 2014
     */
    public void setNewsFetchTime(Date newsFetchTime) {
        this.newsFetchTime = newsFetchTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_detail_backup.news_site_name
     *
     * @return the value of news_detail_backup.news_site_name
     * @mbggenerated Mon Dec 08 15:48:54 CST 2014
     */
    public String getNewsSiteName() {
        return newsSiteName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_detail_backup.news_site_name
     *
     * @param newsSiteName the value for news_detail_backup.news_site_name
     * @mbggenerated Mon Dec 08 15:48:54 CST 2014
     */
    public void setNewsSiteName(String newsSiteName) {
        this.newsSiteName = newsSiteName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_detail_backup.news_publish_time
     *
     * @return the value of news_detail_backup.news_publish_time
     * @mbggenerated Mon Dec 08 15:48:54 CST 2014
     */
    public Date getNewsPublishTime() {
        return newsPublishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_detail_backup.news_publish_time
     *
     * @param newsPublishTime the value for news_detail_backup.news_publish_time
     * @mbggenerated Mon Dec 08 15:48:54 CST 2014
     */
    public void setNewsPublishTime(Date newsPublishTime) {
        this.newsPublishTime = newsPublishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_detail_backup.news_comments_num
     *
     * @return the value of news_detail_backup.news_comments_num
     * @mbggenerated Mon Dec 08 15:48:54 CST 2014
     */
    public Integer getNewsCommentsNum() {
        return newsCommentsNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_detail_backup.news_comments_num
     *
     * @param newsCommentsNum the value for news_detail_backup.news_comments_num
     * @mbggenerated Mon Dec 08 15:48:54 CST 2014
     */
    public void setNewsCommentsNum(Integer newsCommentsNum) {
        this.newsCommentsNum = newsCommentsNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_detail_backup.hashValue
     *
     * @return the value of news_detail_backup.hashValue
     * @mbggenerated Mon Dec 08 15:48:54 CST 2014
     */
    public String getHashvalue() {
        return hashvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_detail_backup.hashValue
     *
     * @param hashvalue the value for news_detail_backup.hashValue
     * @mbggenerated Mon Dec 08 15:48:54 CST 2014
     */
    public void setHashvalue(String hashvalue) {
        this.hashvalue = hashvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_detail_backup.has_summary
     *
     * @return the value of news_detail_backup.has_summary
     * @mbggenerated Mon Dec 08 15:48:54 CST 2014
     */
    public Byte getHasSummary() {
        return hasSummary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_detail_backup.has_summary
     *
     * @param hasSummary the value for news_detail_backup.has_summary
     * @mbggenerated Mon Dec 08 15:48:54 CST 2014
     */
    public void setHasSummary(Byte hasSummary) {
        this.hasSummary = hasSummary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_detail_backup.isActive
     *
     * @return the value of news_detail_backup.isActive
     * @mbggenerated Mon Dec 08 15:48:54 CST 2014
     */
    public Byte getIsactive() {
        return isactive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_detail_backup.isActive
     *
     * @param isactive the value for news_detail_backup.isActive
     * @mbggenerated Mon Dec 08 15:48:54 CST 2014
     */
    public void setIsactive(Byte isactive) {
        this.isactive = isactive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_detail_backup.source_type
     *
     * @return the value of news_detail_backup.source_type
     * @mbggenerated Mon Dec 08 15:48:54 CST 2014
     */
    public String getSourceType() {
        return sourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_detail_backup.source_type
     *
     * @param sourceType the value for news_detail_backup.source_type
     * @mbggenerated Mon Dec 08 15:48:54 CST 2014
     */
    public void setSourceType(String sourceType) {
        this.sourceType = sourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_detail_backup.usefull
     *
     * @return the value of news_detail_backup.usefull
     * @mbggenerated Mon Dec 08 15:48:54 CST 2014
     */
    public Byte getUsefull() {
        return usefull;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_detail_backup.usefull
     *
     * @param usefull the value for news_detail_backup.usefull
     * @mbggenerated Mon Dec 08 15:48:54 CST 2014
     */
    public void setUsefull(Byte usefull) {
        this.usefull = usefull;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_detail_backup.group_id
     *
     * @return the value of news_detail_backup.group_id
     * @mbggenerated Mon Dec 08 15:48:54 CST 2014
     */
    public Long getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_detail_backup.group_id
     *
     * @param groupId the value for news_detail_backup.group_id
     * @mbggenerated Mon Dec 08 15:48:54 CST 2014
     */
    public void setGroupId(Long groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_detail_backup.auto_update_time
     *
     * @return the value of news_detail_backup.auto_update_time
     * @mbggenerated Mon Dec 08 15:48:54 CST 2014
     */
    public Date getAutoUpdateTime() {
        return autoUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_detail_backup.auto_update_time
     *
     * @param autoUpdateTime the value for news_detail_backup.auto_update_time
     * @mbggenerated Mon Dec 08 15:48:54 CST 2014
     */
    public void setAutoUpdateTime(Date autoUpdateTime) {
        this.autoUpdateTime = autoUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_detail_backup.page_tag
     *
     * @return the value of news_detail_backup.page_tag
     * @mbggenerated Mon Dec 08 15:48:54 CST 2014
     */
    public String getPageTag() {
        return pageTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_detail_backup.page_tag
     *
     * @param pageTag the value for news_detail_backup.page_tag
     * @mbggenerated Mon Dec 08 15:48:54 CST 2014
     */
    public void setPageTag(String pageTag) {
        this.pageTag = pageTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_detail_backup.news_body
     *
     * @return the value of news_detail_backup.news_body
     * @mbggenerated Mon Dec 08 15:48:54 CST 2014
     */

    public void setInfoType(Integer infoType) {
        this.infoType = infoType;
    }

    public Integer getInfoType(){
        return infoType;
    }

    public Byte getPublishStatus() {
        return publishStatus;
    }

    public void setPublishStatus(Byte publishStatus) {
        this.publishStatus = publishStatus;
    }

    public Integer getIsHeadline() {
        return isHeadline;
    }

    public void setIsHeadline(Integer isHeadline) {
        this.isHeadline = isHeadline;
    }

    public Integer getIsEdited() {
        return isEdited;
    }

    public void setIsEdited(Integer isEdited) {
        this.isEdited = isEdited;
    }

    public String getEditor() {
        return editor;
    }

    public void setEditor(String editor) {
        this.editor = editor;
    }

	public Date getEffectiveTime() {
		return effectiveTime;
	}

	public void setEffectiveTime(Date effectiveTime) {
		this.effectiveTime = effectiveTime;
	}

}
